name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: 'postgres:15'
        env:
          POSTGRES_USER: ci_postgres
          POSTGRES_PASSWORD: ci_postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Copy .env file
        run: |
          cp .env.ci .env
          cp .env.ci .env.testing
          php artisan key:generate
          php artisan key:generate --env=testing

      - name: Run composer
        run: |
          composer install --no-interaction

      - name: Run test suite
        run: |
          php artisan test
        env:
          DB_DATABASE: cicd_testing

      - name: Run Larastan
        run: |
          ./vendor/bin/phpstan analyse